import turtle
turtle=Turtle.Pen()
turtle.circle(90)
turtle.penup()
turtle.stepos(-40,100)
turtle.pendown()
turtle.circle(10)
turtle.penup()
turtle.stepos(40,100)
turtle.pendown()
turtle.circle(10)
turtle.penup()
turtle.stepos(0,10)
turtle.pendown()
for i in range(90):
    turtle.forward(0.8)
    turtle.left(1)
turtle.penup()
turtle.stepos(0,10)
turtle.pendown()
turtle.right(270)
for i in range(90):
    turtle.forward(0.8)
    turtle.right(1)
turtle.right(90)
turtle.forward(93)